# Generated by Django 5.1 on 2024-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transactionhistory_account_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
